# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-06 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel'), ('food', 'Food'), ('places', 'Places')], max_length=20),
        ),
    ]
