# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-08 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20191107_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontAwesome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60)),
            ],
        ),
    ]
