# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-11 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_fontawesome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FontAwesome',
        ),
    ]
